server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:      
- job_name: applicatios-logs
  static_configs:
  - targets:
      - applicatios-logs
    labels:
      job: applicatios-logs
      __path__: "C:/Applications/*/logs/service/serivceLog.log"   